<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250605060632 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE attendance (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, status VARCHAR(255) NOT NULL, student_id INT DEFAULT NULL, class_group_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6DE30D91CB944F1A ON attendance (student_id)');
        $this->addSql('CREATE INDEX IDX_6DE30D914A9A1217 ON attendance (class_group_id)');
        $this->addSql('CREATE TABLE class_group (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, grade_id INT NOT NULL, school_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8B1765F3FE19A1A8 ON class_group (grade_id)');
        $this->addSql('CREATE INDEX IDX_8B1765F3C32A47EE ON class_group (school_id)');
        $this->addSql('CREATE TABLE grade (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, school_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_595AAE34C32A47EE ON grade (school_id)');
        $this->addSql('CREATE TABLE guardian (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE guardian_school (guardian_id INT NOT NULL, school_id INT NOT NULL, PRIMARY KEY(guardian_id, school_id))');
        $this->addSql('CREATE INDEX IDX_A57387AE11CC8B0A ON guardian_school (guardian_id)');
        $this->addSql('CREATE INDEX IDX_A57387AEC32A47EE ON guardian_school (school_id)');
        $this->addSql('CREATE TABLE school (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE student (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, student_code VARCHAR(220) NOT NULL, current_class_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B723AF337778713A ON student (current_class_id)');
        $this->addSql('CREATE TABLE student_guardian (student_id INT NOT NULL, guardian_id INT NOT NULL, PRIMARY KEY(student_id, guardian_id))');
        $this->addSql('CREATE INDEX IDX_D7C32CCECB944F1A ON student_guardian (student_id)');
        $this->addSql('CREATE INDEX IDX_D7C32CCE11CC8B0A ON student_guardian (guardian_id)');
        $this->addSql('CREATE TABLE subject (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE teacher (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE teacher_school (teacher_id INT NOT NULL, school_id INT NOT NULL, PRIMARY KEY(teacher_id, school_id))');
        $this->addSql('CREATE INDEX IDX_EC15084E41807E1D ON teacher_school (teacher_id)');
        $this->addSql('CREATE INDEX IDX_EC15084EC32A47EE ON teacher_school (school_id)');
        $this->addSql('CREATE TABLE teacher_class_group (teacher_id INT NOT NULL, class_group_id INT NOT NULL, PRIMARY KEY(teacher_id, class_group_id))');
        $this->addSql('CREATE INDEX IDX_5D4BD9B941807E1D ON teacher_class_group (teacher_id)');
        $this->addSql('CREATE INDEX IDX_5D4BD9B94A9A1217 ON teacher_class_group (class_group_id)');
        $this->addSql('CREATE TABLE teacher_subject (teacher_id INT NOT NULL, subject_id INT NOT NULL, PRIMARY KEY(teacher_id, subject_id))');
        $this->addSql('CREATE INDEX IDX_360CB33B41807E1D ON teacher_subject (teacher_id)');
        $this->addSql('CREATE INDEX IDX_360CB33B23EDC87 ON teacher_subject (subject_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, student_profile_id INT DEFAULT NULL, teacher_profile_id INT DEFAULT NULL, guardian_profile_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D6492125FF59 ON "user" (student_profile_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D64946E5B018 ON "user" (teacher_profile_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D64946549888 ON "user" (guardian_profile_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('ALTER TABLE attendance ADD CONSTRAINT FK_6DE30D91CB944F1A FOREIGN KEY (student_id) REFERENCES student (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE attendance ADD CONSTRAINT FK_6DE30D914A9A1217 FOREIGN KEY (class_group_id) REFERENCES class_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE class_group ADD CONSTRAINT FK_8B1765F3FE19A1A8 FOREIGN KEY (grade_id) REFERENCES grade (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE class_group ADD CONSTRAINT FK_8B1765F3C32A47EE FOREIGN KEY (school_id) REFERENCES school (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE grade ADD CONSTRAINT FK_595AAE34C32A47EE FOREIGN KEY (school_id) REFERENCES school (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE guardian_school ADD CONSTRAINT FK_A57387AE11CC8B0A FOREIGN KEY (guardian_id) REFERENCES guardian (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE guardian_school ADD CONSTRAINT FK_A57387AEC32A47EE FOREIGN KEY (school_id) REFERENCES school (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student ADD CONSTRAINT FK_B723AF337778713A FOREIGN KEY (current_class_id) REFERENCES class_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student_guardian ADD CONSTRAINT FK_D7C32CCECB944F1A FOREIGN KEY (student_id) REFERENCES student (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student_guardian ADD CONSTRAINT FK_D7C32CCE11CC8B0A FOREIGN KEY (guardian_id) REFERENCES guardian (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE teacher_school ADD CONSTRAINT FK_EC15084E41807E1D FOREIGN KEY (teacher_id) REFERENCES teacher (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE teacher_school ADD CONSTRAINT FK_EC15084EC32A47EE FOREIGN KEY (school_id) REFERENCES school (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE teacher_class_group ADD CONSTRAINT FK_5D4BD9B941807E1D FOREIGN KEY (teacher_id) REFERENCES teacher (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE teacher_class_group ADD CONSTRAINT FK_5D4BD9B94A9A1217 FOREIGN KEY (class_group_id) REFERENCES class_group (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE teacher_subject ADD CONSTRAINT FK_360CB33B41807E1D FOREIGN KEY (teacher_id) REFERENCES teacher (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE teacher_subject ADD CONSTRAINT FK_360CB33B23EDC87 FOREIGN KEY (subject_id) REFERENCES subject (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D6492125FF59 FOREIGN KEY (student_profile_id) REFERENCES student (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D64946E5B018 FOREIGN KEY (teacher_profile_id) REFERENCES teacher (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D64946549888 FOREIGN KEY (guardian_profile_id) REFERENCES guardian (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE attendance DROP CONSTRAINT FK_6DE30D91CB944F1A');
        $this->addSql('ALTER TABLE attendance DROP CONSTRAINT FK_6DE30D914A9A1217');
        $this->addSql('ALTER TABLE class_group DROP CONSTRAINT FK_8B1765F3FE19A1A8');
        $this->addSql('ALTER TABLE class_group DROP CONSTRAINT FK_8B1765F3C32A47EE');
        $this->addSql('ALTER TABLE grade DROP CONSTRAINT FK_595AAE34C32A47EE');
        $this->addSql('ALTER TABLE guardian_school DROP CONSTRAINT FK_A57387AE11CC8B0A');
        $this->addSql('ALTER TABLE guardian_school DROP CONSTRAINT FK_A57387AEC32A47EE');
        $this->addSql('ALTER TABLE student DROP CONSTRAINT FK_B723AF337778713A');
        $this->addSql('ALTER TABLE student_guardian DROP CONSTRAINT FK_D7C32CCECB944F1A');
        $this->addSql('ALTER TABLE student_guardian DROP CONSTRAINT FK_D7C32CCE11CC8B0A');
        $this->addSql('ALTER TABLE teacher_school DROP CONSTRAINT FK_EC15084E41807E1D');
        $this->addSql('ALTER TABLE teacher_school DROP CONSTRAINT FK_EC15084EC32A47EE');
        $this->addSql('ALTER TABLE teacher_class_group DROP CONSTRAINT FK_5D4BD9B941807E1D');
        $this->addSql('ALTER TABLE teacher_class_group DROP CONSTRAINT FK_5D4BD9B94A9A1217');
        $this->addSql('ALTER TABLE teacher_subject DROP CONSTRAINT FK_360CB33B41807E1D');
        $this->addSql('ALTER TABLE teacher_subject DROP CONSTRAINT FK_360CB33B23EDC87');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D6492125FF59');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D64946E5B018');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D64946549888');
        $this->addSql('DROP TABLE attendance');
        $this->addSql('DROP TABLE class_group');
        $this->addSql('DROP TABLE grade');
        $this->addSql('DROP TABLE guardian');
        $this->addSql('DROP TABLE guardian_school');
        $this->addSql('DROP TABLE school');
        $this->addSql('DROP TABLE student');
        $this->addSql('DROP TABLE student_guardian');
        $this->addSql('DROP TABLE subject');
        $this->addSql('DROP TABLE teacher');
        $this->addSql('DROP TABLE teacher_school');
        $this->addSql('DROP TABLE teacher_class_group');
        $this->addSql('DROP TABLE teacher_subject');
        $this->addSql('DROP TABLE "user"');
    }
}
