<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250611141756 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE person (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT DEFAULT NULL, discr VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_34DCD176A76ED395 ON person (user_id)');
        $this->addSql('ALTER TABLE person ADD CONSTRAINT FK_34DCD176A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE grade DROP CONSTRAINT FK_595AAE34C32A47EE');
        $this->addSql('ALTER TABLE grade ADD CONSTRAINT FK_595AAE34C32A47EE FOREIGN KEY (school_id) REFERENCES school (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE guardian ALTER id TYPE INT');
        $this->addSql('ALTER TABLE guardian ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE guardian ADD CONSTRAINT FK_64486055BF396750 FOREIGN KEY (id) REFERENCES person (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F99EDABB5E237E06 ON school (name)');
        $this->addSql('ALTER TABLE student ALTER id TYPE INT');
        $this->addSql('ALTER TABLE student ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE student ADD CONSTRAINT FK_B723AF33BF396750 FOREIGN KEY (id) REFERENCES person (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE teacher ALTER id TYPE INT');
        $this->addSql('ALTER TABLE teacher ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE teacher ADD CONSTRAINT FK_B0F6A6D5BF396750 FOREIGN KEY (id) REFERENCES person (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT fk_8d93d6492125ff59');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT fk_8d93d64946e5b018');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT fk_8d93d64946549888');
        $this->addSql('DROP INDEX uniq_8d93d64946549888');
        $this->addSql('DROP INDEX uniq_8d93d64946e5b018');
        $this->addSql('DROP INDEX uniq_8d93d6492125ff59');
        $this->addSql('ALTER TABLE "user" DROP student_profile_id');
        $this->addSql('ALTER TABLE "user" DROP teacher_profile_id');
        $this->addSql('ALTER TABLE "user" DROP guardian_profile_id');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE person DROP CONSTRAINT FK_34DCD176A76ED395');
        $this->addSql('DROP TABLE person');
        $this->addSql('ALTER TABLE teacher DROP CONSTRAINT FK_B0F6A6D5BF396750');
        $this->addSql('ALTER TABLE teacher ALTER id TYPE INT');
        $this->addSql('ALTER TABLE teacher ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE grade DROP CONSTRAINT fk_595aae34c32a47ee');
        $this->addSql('ALTER TABLE grade ADD CONSTRAINT fk_595aae34c32a47ee FOREIGN KEY (school_id) REFERENCES school (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('DROP INDEX UNIQ_F99EDABB5E237E06');
        $this->addSql('ALTER TABLE guardian DROP CONSTRAINT FK_64486055BF396750');
        $this->addSql('ALTER TABLE guardian ALTER id TYPE INT');
        $this->addSql('ALTER TABLE guardian ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE "user" ADD student_profile_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD teacher_profile_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD guardian_profile_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT fk_8d93d6492125ff59 FOREIGN KEY (student_profile_id) REFERENCES student (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT fk_8d93d64946e5b018 FOREIGN KEY (teacher_profile_id) REFERENCES teacher (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT fk_8d93d64946549888 FOREIGN KEY (guardian_profile_id) REFERENCES guardian (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE UNIQUE INDEX uniq_8d93d64946549888 ON "user" (guardian_profile_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_8d93d64946e5b018 ON "user" (teacher_profile_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_8d93d6492125ff59 ON "user" (student_profile_id)');
        $this->addSql('ALTER TABLE student DROP CONSTRAINT FK_B723AF33BF396750');
        $this->addSql('ALTER TABLE student ALTER id TYPE INT');
        $this->addSql('ALTER TABLE student ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
    }
}
